name: Blog Post
description: Create a new blog post
title: "Insert the title here"
labels: ["blogpost"]
body:
  - type: input
    id: slug
    attributes:
      label: Slug
      description: The post slug
      placeholder: my-blog-post
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Date
      description: The publication date
      placeholder: YYYY-MM-DD
    validations:
      required: true
  - type: dropdown
    id: tags
    attributes:
      label: Tags
      description: The tags
      multiple: true
      options:
        - label: VMware
        - label: Cloud
  - type: textarea
    id: excerpt
    attributes:
      label: Excerpt
      description: The excerpt. Kepp it short and one line max
      placeholder: In this post...
    validations:
      required: true
  - type: textarea
    id: body
    attributes:
      label: Body
      description: The body of the content
      value: |
        This is the whole content of the post!
