name: Content Upsert

on:
  issues:
    types: 
    - opened
    - edited
    - delete

jobs:
  setup_repo:
    runs-on: ubuntu-latest
    steps:
    - run: echo '${{toJSON(github.event)}}'
    - run: exit 0
      if: ${{ ! contains(github.event.issue.labels[0].name, 'type:') }}

    - id: type
      run: |
        type=$(echo ${{ github.event.issue.labels[0].name }} | cut -d ':' -f2)
        echo "value=$type" >> $GITHUB_OUTPUT
    
    - id: title
      run: |
        echo "value=${{github.event.issue.title}}" >> $GITHUB_OUTPUT

    - uses: actions/checkout@v3
  
    - uses: stefanbuck/github-issue-praser@v3
      id: issue
      with:
        template-path: ".github/ISSUE_TEMPLATE/${{steps.type.outputs.value}}.yaml"

    - run: echo "${{steps.issue.outputs.issueparser_slug}}"

    - name: Commit changes
      shell: bash
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add .
        git commit -m "Change post ${{steps.issue-parser.outputs.issueparser_slug}}"
        git push
