name: Post Upsert

on:
  issues:
    types: 
    - opened
    - edited

jobs:
  setup_repo:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{toJSON(github.event.issue.labels)}}"

    - run: exit 0
      if: ${{ ! contains(github.event.issue.labels[0].name, 'type:') }}

    - id: type
      run: |
        type=$(echo ${{ github.event.issue.labels[0].name }} | cut -d ':' -f2)
        echo "::set-output name=value::$type"

    - run: echo "${{steps.type.outputs.value}}"

    - uses: actions/checkout@v2
  
    - uses: stefanbuck/github-issue-praser@v2
      id: issue
      with:
        template-path: ".github/ISSUE_TEMPLATE/${{steps.type.outputs.value}}.yaml"

    - run: echo "${{steps.issue.outputs.issueparser_title}}"

    - name: Commit changes
      shell: bash
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add .
        git commit -m "Change post ${{steps.issue-parser.outputs.issueparser_title}}"
        git push
